### ISSUE TITLE
SDL library

### ISSUE THREAD

**Issue by littlebalup** [usineur/ZeldaROTH#1]
Salut,
Could you share the SDL lib you used? I only found SDL2 lib publicly ported to VITA.

Merci :)

**Comment by usineur** [comment]
hi,

ZeldROTH doesn't use SDL2 but SDL(1). You can clone https://github.com/Cpasjuste/SDL-Vita and checkout to *SDL12* branch, and then compile it by yourself.

You also need SDL_gfx, SDL_mixer and SDL_image, not the 2.0 versions.

You can also have them using this: https://github.com/vitasdk/vdpm

Whatever, my pre-compiled libs are available here: https://ferb.fr/vita/sdl_vita.zip

**Comment by littlebalup** [comment]
Thank you very much, compilation succeded using your pre-compiled libs :)
